import { ValidationRule } from './validationEngine';
import {
  REQUIRED_QUESTION_FIELD,
  UNKNOWN_QUESTION_TYPE_BLOCK,
  EMPTY_ROW_WARNING,
  DUPLICATE_QUESTION_ID,
  DUPLICATE_NORMALIZED_STEM_REVIEW,
  LATEX_DELIMITER_UNCLOSED,
  MEDIA_URL_INVALID_FORMAT,
  MARKS_INVALID,
  NEGATIVE_MARKS_INVALID,
  YEAR_INVALID
} from '../rules/general.rules';

import {
  MCQ_MIN_OPTIONS,
  MCQ_OPTION_TEXT_NOT_EMPTY,
  MCQ_OPTIONS_UNIQUE,
  MCQ_OPTION_IDENTIFIERS_UNIQUE,
  MCQ_OPTION_IDENTIFIER_VALID,
  MCQ_HAS_CORRECT_ANSWER,
  MCQ_ANSWER_IN_OPTIONS,
  MCQ_ANSWER_TEXT_MATCH,
  MCQ_ANSWER_TEXT_AMBIGUOUS,
  MCQ_SINGLE_CORRECT_ONLY,
  MCQ_SHOULD_BE_MSQ_REVIEW,
  MCQ_SUSPECT_TRUE_FALSE_REVIEW
} from '../rules/mcq.rules';

import {
  MSQ_MIN_OPTIONS,
  MSQ_HAS_CORRECT_ANSWERS,
  MSQ_ANSWER_IDENTIFIER_VALID,
  MSQ_OPTION_IDENTIFIERS_UNIQUE,
  MSQ_OPTIONS_UNIQUE,
  MSQ_CORRECT_ANSWERS_IN_OPTIONS,
  MSQ_MIXED_IDENTIFIER_MODE,
  MSQ_ANSWER_TEXT_MATCH,
  MSQ_ANSWER_TEXT_AMBIGUOUS,
  MSQ_NO_DUPLICATE_CORRECT_ANSWERS,
  MSQ_EXACT_SET_MATCH,
  DELIMITER_FORMAT_FOR_MSQ,
  MSQ_SCORING_REVIEW
} from '../rules/msq.rules';

import {
  TEXT_ENTRY_HAS_ANSWER,
  TEXT_ENTRY_ACCEPTED_ANSWERS_NOT_EMPTY,
  TEXT_ENTRY_MULTIPLE_ANSWERS_DELIMITER_VALID,
  TEXT_ENTRY_CASE_POLICY_DEFINED,
  TEXT_ENTRY_TRIM_POLICY_DEFINED,
  TEXT_ENTRY_NUMERIC_ANSWER_VALID,
  TEXT_ENTRY_NUMERIC_TOLERANCE_VALID,
  TEXT_ENTRY_UNIT_POLICY_VALID,
  TEXT_ENTRY_FORMULA_FORMAT_VALID,
  TEXT_ENTRY_LATEX_VALID
} from '../rules/textEntry.rules';

import {
  ORDER_MIN_OPTIONS,
  ORDER_HAS_CORRECT_SEQUENCE,
  ORDER_SEQUENCE_MATCH
} from '../rules/order.rules';

export const defaultRules: ValidationRule[] = [
  REQUIRED_QUESTION_FIELD,
  UNKNOWN_QUESTION_TYPE_BLOCK,
  EMPTY_ROW_WARNING,
  DUPLICATE_QUESTION_ID,
  DUPLICATE_NORMALIZED_STEM_REVIEW,
  LATEX_DELIMITER_UNCLOSED,
  MEDIA_URL_INVALID_FORMAT,
  MARKS_INVALID,
  NEGATIVE_MARKS_INVALID,
  YEAR_INVALID,

  // MCQ Rules
  MCQ_MIN_OPTIONS,
  MCQ_OPTION_TEXT_NOT_EMPTY,
  MCQ_OPTIONS_UNIQUE,
  MCQ_OPTION_IDENTIFIERS_UNIQUE,
  MCQ_OPTION_IDENTIFIER_VALID,
  MCQ_HAS_CORRECT_ANSWER,
  MCQ_ANSWER_IN_OPTIONS,
  MCQ_ANSWER_TEXT_MATCH,
  MCQ_ANSWER_TEXT_AMBIGUOUS,
  MCQ_SINGLE_CORRECT_ONLY,
  MCQ_SHOULD_BE_MSQ_REVIEW,
  MCQ_SUSPECT_TRUE_FALSE_REVIEW,

  // MSQ Rules
  MSQ_MIN_OPTIONS,
  MSQ_HAS_CORRECT_ANSWERS,
  MSQ_ANSWER_IDENTIFIER_VALID,
  MSQ_OPTION_IDENTIFIERS_UNIQUE,
  MSQ_OPTIONS_UNIQUE,
  MSQ_CORRECT_ANSWERS_IN_OPTIONS,
  MSQ_MIXED_IDENTIFIER_MODE,
  MSQ_ANSWER_TEXT_MATCH,
  MSQ_ANSWER_TEXT_AMBIGUOUS,
  MSQ_NO_DUPLICATE_CORRECT_ANSWERS,
  MSQ_EXACT_SET_MATCH,
  DELIMITER_FORMAT_FOR_MSQ,
  MSQ_SCORING_REVIEW,

  // TEXT_ENTRY Rules
  TEXT_ENTRY_HAS_ANSWER,
  TEXT_ENTRY_ACCEPTED_ANSWERS_NOT_EMPTY,
  TEXT_ENTRY_MULTIPLE_ANSWERS_DELIMITER_VALID,
  TEXT_ENTRY_CASE_POLICY_DEFINED,
  TEXT_ENTRY_TRIM_POLICY_DEFINED,
  TEXT_ENTRY_NUMERIC_ANSWER_VALID,
  TEXT_ENTRY_NUMERIC_TOLERANCE_VALID,
  TEXT_ENTRY_UNIT_POLICY_VALID,
  TEXT_ENTRY_FORMULA_FORMAT_VALID,
  TEXT_ENTRY_LATEX_VALID,

  // ORDER Rules
  ORDER_MIN_OPTIONS,
  ORDER_HAS_CORRECT_SEQUENCE,
  ORDER_SEQUENCE_MATCH
];

export function getDefaultRuleRegistry(): ValidationRule[] {
  return [...defaultRules];
}
