import { ValidationRule } from "./validationEngine";
import { canonicalRuleCatalog } from "./canonicalRuleCatalog";
import { createCanonicalRule } from "./canonicalRuleFactory";
import {
  REQUIRED_QUESTION_FIELD,
  UNKNOWN_QUESTION_TYPE_BLOCK,
  EMPTY_ROW_WARNING,
  DUPLICATE_QUESTION_ID,
  DUPLICATE_NORMALIZED_STEM_REVIEW,
  LATEX_STEM_DELIMITER_VALID,
  MEDIA_URL_INVALID_FORMAT,
  MARKS_INVALID,
  NEGATIVE_MARKS_INVALID,
  TIME_LIMIT_INVALID,
  YEAR_INVALID,
} from "../rules/general.rules";

import {
  MCQ_MIN_OPTIONS,
  MCQ_OPTION_TEXT_NOT_EMPTY,
  MCQ_OPTIONS_UNIQUE,
  MCQ_OPTION_IDENTIFIERS_UNIQUE,
  MCQ_OPTION_IDENTIFIER_VALID,
  MCQ_HAS_CORRECT_ANSWER,
  MCQ_ANSWER_IN_OPTIONS,
  MCQ_ANSWER_TEXT_MATCH,
  MCQ_ANSWER_TEXT_AMBIGUOUS,
  MCQ_SINGLE_CORRECT_ONLY,
  MCQ_SHOULD_BE_MSQ_REVIEW,
  MCQ_SUSPECT_TRUE_FALSE_REVIEW,
} from "../rules/mcq.rules";

import {
  MSQ_MIN_OPTIONS,
  MSQ_HAS_CORRECT_ANSWERS,
  MSQ_ANSWER_IDENTIFIER_VALID,
  MSQ_OPTION_IDENTIFIERS_UNIQUE,
  MSQ_OPTIONS_UNIQUE,
  MSQ_CORRECT_ANSWERS_IN_OPTIONS,
  MSQ_MIXED_IDENTIFIER_MODE,
  MSQ_ANSWER_TEXT_MATCH,
  MSQ_ANSWER_TEXT_AMBIGUOUS,
  MSQ_NO_DUPLICATE_CORRECT_ANSWERS,
  MSQ_EXACT_SET_MATCH,
  DELIMITER_FORMAT_FOR_MSQ,
  MSQ_SCORING_REVIEW,
} from "../rules/msq.rules";

import {
  TEXT_ENTRY_HAS_ANSWER,
  TEXT_ENTRY_ACCEPTED_ANSWERS_NOT_EMPTY,
  TEXT_ENTRY_MULTIPLE_ANSWERS_DELIMITER_VALID,
  TEXT_ENTRY_CASE_POLICY_DEFINED,
  TEXT_ENTRY_TRIM_POLICY_DEFINED,
  TEXT_ENTRY_NUMERIC_ANSWER_VALID,
  TEXT_ENTRY_NUMERIC_TOLERANCE_VALID,
  TEXT_ENTRY_UNIT_POLICY_VALID,
  TEXT_ENTRY_FORMULA_FORMAT_VALID,
  TEXT_ENTRY_LATEX_VALID,
} from "../rules/textEntry.rules";

import {
  ORDER_MIN_OPTIONS,
  ORDER_HAS_CORRECT_SEQUENCE,
  ORDER_SEQUENCE_MATCH,
} from "../rules/order.rules";

import {
  COLUMN_MAPPING_AMBIGUOUS,
  QUESTION_ID_FIELD_MISMAPPED,
  QUESTION_TYPE_ALIAS_UNMAPPED,
  EXPLICIT_TYPE_OVERRIDDEN,
  RESPONSE_SUBTYPE_LOST,
  NEGATIVE_MARKS_CONVENTION_AMBIGUOUS,
  NORMALIZATION_AUDIT_MISSING,
} from "../rules/ingestion.rules";

import {
  NUMERIC_ANSWER_NOT_NUMERIC,
  INTEGER_ANSWER_NOT_INTEGER,
  NUMERIC_TOLERANCE_MISSING,
  NUMERIC_TOLERANCE_INVALID,
  UNIT_EMBEDDED_IN_NUMERIC_ANSWER,
  INACTIVE_FIELD_CONTAINS_DATA,
  UNIT_POLICY_INVALID,
  POSITIVE_MARKS_INVALID,
  NEGATIVE_MARKS_EXCEED_POSITIVE,
  QUESTION_SCORING_CONFLICTS_WITH_SECTION,
  PARTIAL_MARKING_AMBIGUOUS,
} from "../rules/numericScoring.rules";

import {
  EXPLANATION_MISSING,
  EXPLANATION_INSUFFICIENT,
  EXPLANATION_KEY_MISMATCH,
  EXPLANATION_RESULT_MISMATCH,
  POSSIBLE_EXPLANATION_RESULT_MISMATCH,
  EXPLANATION_FORMAT_INCOMPATIBLE,
  EXPLANATION_UNIT_MISMATCH,
  MULTIPLE_CORRECT_OPTIONS_SUSPECTED,
} from "../rules/explanationAcademic.rules";

import {
  MALFORMED_LATEX_DELIMITER,
  MATH_RENDER_FAILED,
  UNSUPPORTED_MATH_FORMAT,
  UNICODE_MATH_FALSE_POSITIVE,
  LANGUAGE_METADATA_MISMATCH,
  UNSUPPORTED_HTML_OR_SCRIPT,
} from "../rules/renderingLanguage.rules";

import {
  MATRIX_MATCH_INCOMPLETE,
  HOTSPOT_CONFIGURATION_INCOMPLETE,
  ORDER_SEQUENCE_INVALID,
  PASSAGE_LINK_BROKEN,
} from "../rules/advancedLinked.rules";

import {
  REPORT_FIELD_MISLABELED,
  ISSUE_MESSAGE_TRUNCATED,
  DUPLICATE_MATCH_CONTEXT_MISSING,
  CORRECTION_ACTION_AMBIGUOUS,
  CORRECTION_AUDIT_TRAIL_MISSING,
} from "../rules/defectReport.rules";

import {
  TRUNCATED_STEM,
  CONTEXT_MISSING,
  BROKEN_ENCODING,
} from "../rules/contentIntegrity.rules";

import {
  REQUIRED_MEDIA_MISSING,
  MEDIA_REFERENCE_NOT_FOUND,
} from "../rules/media.rules";

import {
  COPYRIGHT_UNVERIFIED,
  AMBIGUOUS_MEDIA_FILENAME,
  WRONG_SUBJECT_TAG,
  NONSTANDARD_DIFFICULTY,
  VERSION_TIMESTAMP_CONFLICT,
  PARTIAL_MARKING_AMBIGUOUS_PROSE,
} from "../rules/complianceMetadata.rules";

import { UNSUPPORTED_TYPE_FOR_TARGET_EXPORT } from "../rules/ingestion.rules";

const legacyRules: ValidationRule[] = [
  // General & Structural
  REQUIRED_QUESTION_FIELD,
  UNKNOWN_QUESTION_TYPE_BLOCK,
  UNSUPPORTED_TYPE_FOR_TARGET_EXPORT,
  EMPTY_ROW_WARNING,
  DUPLICATE_QUESTION_ID,
  DUPLICATE_NORMALIZED_STEM_REVIEW,
  LATEX_STEM_DELIMITER_VALID,
  MEDIA_URL_INVALID_FORMAT,
  MARKS_INVALID,
  NEGATIVE_MARKS_INVALID,
  TIME_LIMIT_INVALID,
  YEAR_INVALID,

  // Content Integrity & Media
  TRUNCATED_STEM,
  CONTEXT_MISSING,
  BROKEN_ENCODING,
  REQUIRED_MEDIA_MISSING,
  MEDIA_REFERENCE_NOT_FOUND,

  // Compliance & Metadata
  COPYRIGHT_UNVERIFIED,
  AMBIGUOUS_MEDIA_FILENAME,
  WRONG_SUBJECT_TAG,
  NONSTANDARD_DIFFICULTY,
  VERSION_TIMESTAMP_CONFLICT,
  PARTIAL_MARKING_AMBIGUOUS_PROSE,

  // Ingestion & Normalization
  COLUMN_MAPPING_AMBIGUOUS,
  QUESTION_ID_FIELD_MISMAPPED,
  QUESTION_TYPE_ALIAS_UNMAPPED,
  EXPLICIT_TYPE_OVERRIDDEN,
  RESPONSE_SUBTYPE_LOST,
  NEGATIVE_MARKS_CONVENTION_AMBIGUOUS,
  NORMALIZATION_AUDIT_MISSING,

  // MCQ Rules
  MCQ_MIN_OPTIONS,
  MCQ_OPTION_TEXT_NOT_EMPTY,
  MCQ_OPTIONS_UNIQUE,
  MCQ_OPTION_IDENTIFIERS_UNIQUE,
  MCQ_OPTION_IDENTIFIER_VALID,
  MCQ_HAS_CORRECT_ANSWER,
  MCQ_ANSWER_IN_OPTIONS,
  MCQ_ANSWER_TEXT_MATCH,
  MCQ_ANSWER_TEXT_AMBIGUOUS,
  MCQ_SINGLE_CORRECT_ONLY,
  MCQ_SHOULD_BE_MSQ_REVIEW,
  MCQ_SUSPECT_TRUE_FALSE_REVIEW,

  // MSQ Rules
  MSQ_MIN_OPTIONS,
  MSQ_HAS_CORRECT_ANSWERS,
  MSQ_ANSWER_IDENTIFIER_VALID,
  MSQ_OPTION_IDENTIFIERS_UNIQUE,
  MSQ_OPTIONS_UNIQUE,
  MSQ_CORRECT_ANSWERS_IN_OPTIONS,
  MSQ_MIXED_IDENTIFIER_MODE,
  MSQ_ANSWER_TEXT_MATCH,
  MSQ_ANSWER_TEXT_AMBIGUOUS,
  MSQ_NO_DUPLICATE_CORRECT_ANSWERS,
  MSQ_EXACT_SET_MATCH,
  DELIMITER_FORMAT_FOR_MSQ,
  MSQ_SCORING_REVIEW,

  // TEXT_ENTRY Rules
  TEXT_ENTRY_HAS_ANSWER,
  TEXT_ENTRY_ACCEPTED_ANSWERS_NOT_EMPTY,
  TEXT_ENTRY_MULTIPLE_ANSWERS_DELIMITER_VALID,
  TEXT_ENTRY_CASE_POLICY_DEFINED,
  TEXT_ENTRY_TRIM_POLICY_DEFINED,
  TEXT_ENTRY_NUMERIC_ANSWER_VALID,
  TEXT_ENTRY_NUMERIC_TOLERANCE_VALID,
  TEXT_ENTRY_UNIT_POLICY_VALID,
  TEXT_ENTRY_FORMULA_FORMAT_VALID,
  TEXT_ENTRY_LATEX_VALID,

  // Numeric Responses, Units & Scoring
  NUMERIC_ANSWER_NOT_NUMERIC,
  INTEGER_ANSWER_NOT_INTEGER,
  NUMERIC_TOLERANCE_MISSING,
  NUMERIC_TOLERANCE_INVALID,
  UNIT_EMBEDDED_IN_NUMERIC_ANSWER,
  INACTIVE_FIELD_CONTAINS_DATA,
  UNIT_POLICY_INVALID,
  POSITIVE_MARKS_INVALID,
  NEGATIVE_MARKS_EXCEED_POSITIVE,
  QUESTION_SCORING_CONFLICTS_WITH_SECTION,
  PARTIAL_MARKING_AMBIGUOUS,

  // ORDER Rules
  ORDER_MIN_OPTIONS,
  ORDER_HAS_CORRECT_SEQUENCE,
  ORDER_SEQUENCE_MATCH,

  // Explanation & Academic Consistency
  EXPLANATION_MISSING,
  EXPLANATION_INSUFFICIENT,
  EXPLANATION_KEY_MISMATCH,
  EXPLANATION_RESULT_MISMATCH,
  POSSIBLE_EXPLANATION_RESULT_MISMATCH,
  EXPLANATION_FORMAT_INCOMPATIBLE,
  EXPLANATION_UNIT_MISMATCH,
  MULTIPLE_CORRECT_OPTIONS_SUSPECTED,

  // Math, Language & Rendering
  MALFORMED_LATEX_DELIMITER,
  MATH_RENDER_FAILED,
  UNSUPPORTED_MATH_FORMAT,
  UNICODE_MATH_FALSE_POSITIVE,
  LANGUAGE_METADATA_MISMATCH,
  UNSUPPORTED_HTML_OR_SCRIPT,

  // Advanced & Linked Content
  MATRIX_MATCH_INCOMPLETE,
  HOTSPOT_CONFIGURATION_INCOMPLETE,
  ORDER_SEQUENCE_INVALID,
  PASSAGE_LINK_BROKEN,

  // Defect & Audit Rules
  REPORT_FIELD_MISLABELED,
  ISSUE_MESSAGE_TRUNCATED,
  DUPLICATE_MATCH_CONTEXT_MISSING,
  CORRECTION_ACTION_AMBIGUOUS,
  CORRECTION_AUDIT_TRAIL_MISSING,
];

const legacyRuleById = new Map(
  legacyRules.map((rule) => [rule.id, rule] as const),
);

export const defaultRules: ValidationRule[] = canonicalRuleCatalog.map((spec) =>
  createCanonicalRule(spec, legacyRuleById.get(spec.id)),
);

export function getDefaultRuleRegistry(): ValidationRule[] {
  return [...defaultRules];
}
